version: '3'

volumes:
  keycloak-db-data:
    driver: local

services:
  postgres:
    image: postgres:13.7
    container_name: postgres
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: K3yCl4k
  keycloak:
    build: .
    container_name: custom-auth-service
    environment:
      #Admin Credentials
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KC_DB_URL: 'jdbc:postgresql://postgres/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: K3yCl4k
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME: localhost
      PROXY_ADDRESS_FORWARDING: "true"
    command:
      - "-v start --optimized"
    ports:
      - 8082:8443
      - 8081:8080
    depends_on:
      - postgres